server:
  port: 8082

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            -Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka/

